import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const popppins = Poppins({ subsets: ['latin'], weight: ['300', '500', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${popppins.className} h-full py-20`}>{children}</body>
    </html>
  )
}
